### PR TITLE
add request session object

### PR DESCRIPTION
**Pull request by wallies**
Fixes https://github.com/chargebee/chargebee-python/issues/44 and https://github.com/chargebee/chargebee-python/issues/30

### CODE REVIEW

**Comment by rcoup** [comment]
IMO this should default to off/disabled with a sensible timeout with no retries — I don't want a webserver sitting there doing try after try to Chargebee with a client waiting for it. The application needs to handle Chargebee errors regardless, so it doesn't simplify logic in the application at all.

Should probably handle `429` errors from hitting the rate limits as well?

Not sure if Chargebee currently supports [idempotency keys ala Stripe](https://stripe.com/docs/api/idempotent_requests) but that would allow retries for POST/PUT/DELETE requests too.

**Comment by wallies** [comment]
@rcoup ive disabled retries by default, but imho retries with backoff should be default behavior. It should be enabled by default in requests, to give as many people as possible this functionality, and then people who dont want it can turn it off. Network is never reliable enough to not have something like this and for me it greatly simplifies my application.

**Comment by cjrh** [comment]
Another idea here is to add a new kwarg with a user-specified requests Session object, defaulting to None. Then only this part (I think) of the existing code needs to change:

```python
def request(method, url, env, params=None, headers=None, session=None):
    ...
    if session:
        response = session.request(**request_args)
    else:
        response = requests.request(**request_args)
```

This way users can set up the retry facility, as well as anything else that sessions allow, however they want.

As a side effect, this also makes testing a bit easier because of the dependency injection. You wouldn't need to mock requests implicitly.

**Comment by wallies** [comment]
@cb-rakesh  @cb-goutham how do we get this merged, as we have had quite a few 

Remote end closed connection and connection reset by peer lately, which we can deal with a lot easier having the request session available.

**Comment by cjrh** [comment]
The PR looks good 👍🏼

**Comment by Aiden0** [comment]
I too would like this PR to be merged please.

**Comment by wallies** [comment]
We have had so many more 504 & 500 errors recently, we decided to upload the fork to pypi for now https://pypi.org/project/secure-chargebee/

**Comment by cb-prajaktachavan** [comment]
This has been merged in v2.11.0. You can set own http connect and read timeouts using chargebee.update_connect_timeout_secs() and chargebee.update_read_timeout_secs().

**Pull request closed without merging**
