### PR TITLE
Fix AttributeError: module 'chargebee' has no attribute 'Usage'

### PR DESCRIPTION
**Pull request by manny-cuboh**
init was missing the usage model so unable to access that attribute, this fixes that

https://github.com/chargebee/chargebee-python/issues/40

### CODE REVIEW

**Comment by adamdubicki** [comment]
@cb-navaneedhan - could have a look at this issue please? It is blocking our integration.

**Comment by MAndresSL** [comment]
This issue is blocking our implementation too.

**Comment by JuanC-Fandino** [comment]
Is blocking our implementation too...

**Comment by cb-goutham** [comment]
This has been fixed in the latest version of SDK - v2.8.4

**Pull request closed without merging**
