### PR TITLE
fixing code to suport python 3

### PR DESCRIPTION
**Pull request by JohnCoogan**
This code fixes syntax errors that break compatibility with Python 3.

### CODE REVIEW

**Comment by ziXet** [comment]
Hi,
I'm getting the following errors in python3.4.

>>> list = chargebee.Customer.list({"limit" : 5})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.4/site-packages/chargebee-1.4.1-py3.4.egg/chargebee/models/customer.py", line 24, in list
    return request.send('get', request.uri_path("customers"), params, env)
  File "/usr/lib/python3.4/site-packages/chargebee-1.4.1-py3.4.egg/chargebee/request.py", line 12, in send
    ser_params = util.serialize(params)
  File "/usr/lib/python3.4/site-packages/chargebee-1.4.1-py3.4.egg/chargebee/util.py", line 15, in serialize
    serialized.update({key: get_val(v)})
  File "/usr/lib/python3.4/site-packages/chargebee-1.4.1-py3.4.egg/chargebee/util.py", line 35, in get_val
    elif isinstance(val, unicode):
NameError: name 'unicode' is not defined

**Comment by saravana-cb** [comment]
Hello Zixet,

Apologies for the inconvenience. Thanks for letting us know the issue you faced. 

We will update the code and give you an update.

**Comment by saravana-cb** [comment]
Hello Zixet,
We have pushed the updated code. Please try it out and let us know if you have any questions.

**Comment by saravana-cb** [comment]
Hello John,
We made the changes to support python 3. Please try it out and let us know so that we could close the pull request.

**Comment by ziXet** [comment]
Thank you. It works now.

**Pull request closed without merging**
