### PR TITLE
migrate to python-requests http lib

### LINKED ISSUE #15: Move from urllib to requests
Hi, I see the lib uses urllib. Would you be open to a switch to requests (https://github.com/request/request)?

Besides the nice api, if chargebee-python used requests it could benefit from other nice libraries like:

- requests cache https://pypi.python.org/pypi/requests-cache
- vcrpy https://github.com/kevin1024/vcrpy (which doesn't support urllib, unfortunately)

Thoughts?

### PR DESCRIPTION
**Pull request by tysonholub**
Hi! This PR migrates to the [python-requests](https://github.com/psf/requests) http library to facilitate writing tests using tools like [vcrpy](https://github.com/kevin1024/vcrpy) and [requests-mock](https://github.com/jamielennox/requests-mock). This closes #15 and removes the need for #24.

### CODE REVIEW

**Comment by jeking3** [comment]
My unit tests suffer with Chargebee because of the issue this fixes.  Will the maintainers please consider merging this?

**Comment by jeking3** [comment]
@tysonholub removing the logging that was added would be prudent; it is not typical to log the request/response with a payment processor and dump a bunch of PII to logs.

**Comment by jeking3** [comment]
I have successfully used this change to enable vcrpy recording of chargebee interactions, and agree with the author's original assessment in the description about what it fixes and obviates.  The only concern is the addition of debug logging of every chargebee request and response.

**Comment by cb-goutham** [comment]
This has been addressed in the latest version - v2.8.4. @tysonholub Thanks for your contribution .

**Pull request closed without merging**
